// Generated by CoffeeScript 1.3.3
(function() {
  var Prediction, app, db, mongoose;

  mongoose = require('mongoose');

  app = require('express')();

  db = mongoose.createConnection('localhost', 'mbtapp');

  db.on('error', function() {
    return console.log('DB connection error');
  });

  Prediction = mongoose.Schema.Types.ObjectId;

  db.once('open', function() {
    var stopSchema;
    console.log('DB connection successful');
    return stopSchema = new mongoose.Schema({
      stopID: Number,
      lastCached: Date,
      Predictions: {}
    });
  });

  app.get('/', function(req, res) {
    return res.send('<h1>Hello</h1><p>Hello, app!</p>');
  });

  app.listen(3000);

  console.log('Listening on port 3000');

}).call(this);
